CREATE TABLE IF NOT EXISTS Users(
  id NUMERIC IDENTITY PRIMARY KEY,
  login VARCHAR(512) NOT NULL,
  password VARCHAR(512) NOT NULL,
  role VARCHAR(512) NOT NULL,

);

CREATE TABLE IF NOT EXISTS RegisteredEvents(
  id NUMERIC IDENTITY PRIMARY KEY,
  parameter VARCHAR(512) NOT NULL,
  value VARCHAR(512) NOT NULL,
  ipAddress VARCHAR(512) NOT NULL,
  date TIMESTAMP NOT NULL,
);